version: '2.1'

networks:
  servers:
    driver: bridge

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    working_dir: /go/src/practice-4
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer
    environment:
      - BALANCER_URL=http://balancer:8090
      - INTEGRATION_TEST=1
    command: ["go", "test", "-v", "./integration/..."]
