version: '2.1'

networks:
  servers:
    driver: bridge

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - servers
    command: ["lb", "--trace=true"]

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - servers
    environment:
      - CONF_RESPONSE_DELAY_SEC=1

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - servers
    environment:
      - CONF_RESPONSE_DELAY_SEC=1

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - servers
    environment:
      - CONF_RESPONSE_DELAY_SEC=1