# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8090:8090
          - 8080:8080
          - 8081:8081
          - 8082:8082

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Run unit tests
      run: go test -v ./cmd/lb

    - name: Build Docker images
      run: docker-compose -f docker-compose.yaml build

    - name: Run integration tests
      run: |
        docker-compose -f docker-compose.yaml up -d
        sleep 10 # Wait for services to start
        docker-compose -f docker-compose.test.yaml run -e INTEGRATION_TEST=1 integration
